### ISSUE TITLE
Output broken in 7.1.1

### ISSUE THREAD

**Issue by dan-the-dev** [paratestphp/paratest#742] opened 2023-03-13 10:48 UTC
| Q | A
| --- | ---
| ParaTest version | 7.1.1
| PHPUnit version | 10.0.16
| PHP version | 8.2.0

#### Summary

After the fix for PHPUnit 10.0.16 compatibility, tests are back to green but the output is weird, it reaches 775% like if tests are executed multiple times. 

#### Current behavior

Output is weird:

```
ParaTest v7.1.1 upon PHPUnit 10.0.16 by Sebastian Bergmann and contributors.

                                Processes:     4
Runtime:       PHP 8.2.0
Configuration: /home/runner/work/my-bistrot-backend/my-bistrot-backend/phpunit.xml

        .        .        .        .        .        .          61 / 1647 (  3%)
 .        .        .        .        .        .        .       122 / 1647 (  7%)
   .        .        .        .        .        .        .     183 / 1647 ( 11%)
     .        .        .        .        .        .        .   244 / 1647 ( 14%)
       .        .        .        .        .        .          305 / 1647 ( 18%)
.        .        .        .        .        .        .        366 / 1647 ( 22%)
  .        .        .        .        .        .        .      427 / 1647 ( 25%)
    .        .        .        .        .        .        .    488 / 1647 ( 2[9](https://github.com/mymenudev/my-bistrot-backend/actions/runs/4403898009/jobs/7712831634#step:8:10)%)
      .        .        .        .        .        .        .  549 / 1647 ( 33%)
        .        .        .        .        .        .         6[10](https://github.com/mymenudev/my-bistrot-backend/actions/runs/4403898009/jobs/7712831634#step:8:11) / 1647 ( 37%)
 .        .        .        .        .        .        .       671 / 1647 ( 40%)
   .        .        .        .        .        .        .     732 / 1647 ( 44%)
     .        .        .        .        .        .        .   793 / 1647 ( 48%)
       .        .        .        .        .        .          854 / 1647 ( 51%)
.        .        .        .        .        .        .        915 / 1647 ( 55%)
  .        .        .        .        .        .        .      976 / 1647 ( 59%)
    .        .        .        .        .        .        .   1037 / 1647 ( 62%)
      .        .        .        .        .        .        . 1098 / 1647 ( 66%)
        .        .        .        .        .        .        [11](https://github.com/mymenudev/my-bistrot-backend/actions/runs/4403898009/jobs/7712831634#step:8:12)59 / 1647 ( 70%)
 .        .        .        .        .        .        .      [12](https://github.com/mymenudev/my-bistrot-backend/actions/runs/4403898009/jobs/7712831634#step:8:13)20 / 1647 ( 74%)
   .        .        .        .        .        .        .    1281 / 1647 ( 77%)
     .        .        .        .        .        .        .  [13](https://github.com/mymenudev/my-bistrot-backend/actions/runs/4403898009/jobs/7712831634#step:8:14)42 / 1647 ( 81%)
       .        .        .        .        .        .         [14](https://github.com/mymenudev/my-bistrot-backend/actions/runs/4403898009/jobs/7712831634#step:8:15)03 / 1647 ( 85%)
.        .        .        .        .        .        .       1464 / 1647 ( 88%)
  .        .        .        .        .        .        .     [15](https://github.com/mymenudev/my-bistrot-backend/actions/runs/4403898009/jobs/7712831634#step:8:16)25 / [16](https://github.com/mymenudev/my-bistrot-backend/actions/runs/4403898009/jobs/7712831634#step:8:17)47 ( 92%)
    .        .        .        .        .        .        .   1586 / 1647 ( 96%)
      .        .        .        .        .        .        . 1647 / 1647 (100%)
  1648 / 1647 (100%)
  1649 / 1647 (100%)
  1650 / 1647 (100%)
  1651 / 1647 (100%)
  1652 / 1647 (100%)

[...]


. 12766 / 1647 (775%)
  12767 / 1647 (775%)
  12768 / 1647 (775%)
  12769 / 1647 (775%)
  12770 / 1647 (775%)
  12771 / 1647 (775%)
  12772 / 1647 (775%)
  12773 / 1647 (775%)
  12774 / 1647 (775%)
. 12775 / 1647 (775%)

Time: 01:00.396, Memory: 54.00 MB

OK (1647 tests, 5237 assertions)
```

#### How to reproduce: command, code and error stack trace

1. Upgrade to last PHPUnit version
2. Upgrade to PHP 8.2
3. Run Paratest 

#### Expected behavior

A sample of the old, correct output:

```
ParaTest v7.1.0 upon PHPUnit 10.0.15 by Sebastian Bergmann and contributors.

                                Processes:     4
Runtime:       PHP 8.2.0
Configuration: /home/runner/work/my-bistrot-backend/my-bistrot-backend/phpunit.xml

.............................................................   61 / 1647 (  3%)
.............................................................  122 / 1647 (  7%)
.............................................................  183 / 1647 ( 11%)
.............................................................  244 / 1647 ( 14%)
.............................................................  305 / 1647 ( 18%)
.............................................................  366 / 1647 ( 22%)
.............................................................  427 / 1647 ( 25%)
.............................................................  488 / 1647 ( 2[9](https://github.com/mymenudev/my-bistrot-backend/actions/runs/4386150646/jobs/7679807613#step:8:10)%)
.............................................................  549 / 1647 ( 33%)
.............................................................  6[10](https://github.com/mymenudev/my-bistrot-backend/actions/runs/4386150646/jobs/7679807613#step:8:11) / 1647 ( 37%)
.............................................................  671 / 1647 ( 40%)
.............................................................  732 / 1647 ( 44%)
.............................................................  793 / 1647 ( 48%)
.............................................................  854 / 1647 ( 51%)
.............................................................  915 / 1647 ( 55%)
.............................................................  976 / 1647 ( 59%)
............................................................. 1037 / 1647 ( 62%)
............................................................. 1098 / 1647 ( 66%)
............................................................. [11](https://github.com/mymenudev/my-bistrot-backend/actions/runs/4386150646/jobs/7679807613#step:8:12)59 / 1647 ( 70%)
............................................................. [12](https://github.com/mymenudev/my-bistrot-backend/actions/runs/4386150646/jobs/7679807613#step:8:13)20 / 1647 ( 74%)
............................................................. 1281 / 1647 ( 77%)
............................................................. [13](https://github.com/mymenudev/my-bistrot-backend/actions/runs/4386150646/jobs/7679807613#step:8:14)42 / 1647 ( 81%)
............................................................. [14](https://github.com/mymenudev/my-bistrot-backend/actions/runs/4386150646/jobs/7679807613#step:8:15)03 / 1647 ( 85%)
............................................................. 1464 / 1647 ( 88%)
............................................................. [15](https://github.com/mymenudev/my-bistrot-backend/actions/runs/4386150646/jobs/7679807613#step:8:16)25 / [16](https://github.com/mymenudev/my-bistrot-backend/actions/runs/4386150646/jobs/7679807613#step:8:17)47 ( 92%)
............................................................. 1586 / 1647 ( 96%)
............................................................. 1647 / 1647 (100%)


Time: 00:58.391, Memory: 54.00 MB

OK (1647 tests, 5[23](https://github.com/mymenudev/my-bistrot-backend/actions/runs/4386150646/jobs/7679807613#step:8:24)7 assertions)
```

Also attaching images of previous and current output to be sure there are no misunderstanding. (Images are from GitHub Actions, which is using PHP 8.2.3, but I checked the issue locally with 8.2.0). 

![Screenshot 2023-03-13 alle 11 46 13](https://user-images.githubusercontent.com/22500696/224680164-36ed3f33-575c-4d56-a1e8-9843c6a80af5.png)
![Screenshot 2023-03-13 alle 11 47 24](https://user-images.githubusercontent.com/22500696/224680200-9577fcb6-9ede-4742-8721-1d6f7c5fcf55.png)

![Screenshot 2023-03-13 alle 11 47 15](https://user-images.githubusercontent.com/22500696/224680186-5d2c1352-1cd5-4cc4-a1f8-52f30962c355.png)

**Comment by Slamdunk** [comment] 2023-03-13 10:56
Honestly I have no idea what's happening here

**Comment by dan-the-dev** [comment] 2023-03-14 14:48
Will try to give a look when I have time, but yeah... it's weird :D as far as you know, is this happening only to me?

**Comment by momala454** [comment] 2023-03-28 08:29
i have this too.
It looks like it is related to any output during test

**Comment by shawnveltman** [comment] 2023-04-08 23:59
I'm facing the same issue as above.  Possibly just a me-problem, but for additional info, when I tried to downgrade to 7.1.0, I ended up getting separate errors about it not being able to resolve the ErrorHandler class in my Laravel 10 project.

**Comment by stumpc** [comment] 2023-05-18 18:45
I'm also having this issue in a big way:

ParaTest Version: 7.1.4
PHPUnit Version: 10.1.3
PHP Version: 8.2.5

Using this in a Laravel 10 project via `artisan test --parallel`.

I'll see what I can find code-diving later when I'm free to do so.

**Comment by lphilps** [comment] 2023-06-06 18:49
I have this too.  I'm using Laravel version 10.  If I run paratest using PHP v8.1 everything is perfect.  If I switch to PHP v8.2, all the tests still pass, but the output was going crazy as reported above. Paratest correctly determines the correct number of tests in the first line of output, but seems report running way more tests than actually exist.

However, I just discovered something else.  Another side effect of upgrading to PHP v8.2, using Laravel v10, was that it started spewing out a bunch of PHP deprecation warnings.  Well, I just fixed the last of them in our code base, and ... as soon as there were no more deprecation warnings, the paratest output suddenly fixed itself!

But, if I pick any test in my test suite and add this code to it:
```
$foo = 'bar';
logger("Force Deprecation Error: ${foo}");
```
As soon as that test executes, and the deprecation error fires, paratest starts miscounting tests and the output goes crazy.

**Comment by Jean85** [comment] 2023-06-07 11:29
Maybe the issue is in PHPUnit throwing deprecation events in unexpected places? I had similar issues while working on Paraunit, and I've seen deprecation events coming out during tests AND outside of test execution (before setup, between tests etc)

**Comment by Slamdunk** [comment] 2023-06-07 12:24
That's interesting.

To anyone who experienced this issue, even on Laravel: as soon as you are able to reproduce the issue on a public repo, I'll try to fix this right away.

**Comment by lphilps** [comment] 2023-06-12 12:30
Since I have a "reproducible" test case, I decided to attempt to debug this and I think I've discovered (at least part of) the problem, which appears to be in `ResultPrinter::printFeeback` (although I don't think this is the "root cause"). That method contains this code:

```
$feedbackItems = $this->tail($progressFile);
if ($feedbackItems === '') {
    return;
}

$feedbackItems = preg_replace('/ +\\d+ \\/ \\d+ \\( *\\d+%\\)\\s*/', '', $feedbackItems);
assert($feedbackItems !== null);

$actualTestCount = strlen($feedbackItems);
for ($index = 0; $index < $actualTestCount; ++$index) {
    $this->printFeedbackItem($feedbackItems[$index]);
}
```

it appears that normally the `feedbackItems` string is something like:

```
........                                                                                            
        8 / 8 (100%)
```

But, if a PHP deprecation error is encountered during a test `feedbackItems` is:

```
Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /<redacted-path>/tests/Feature/FooTest.php on line 58
.                                                                                                           1 / 1 (100%)
```

after which the preg does the wrong thing because the string it expects to be working on is not at all what it received.

This is almost certainly not the right, or best, fix, but I can mask the symptom of the problem, so that paratest generates the correct output again, by adding this extra line of code right before the preg_replace in the code fragment above:

```
// Remove any PHP deprecation warnings from the feedback before processing it.
$feedbackItems = preg_replace('/\nDeprecated: [^\n]+\n/m', '', $feedbackItems);
```

While that does clean things up, for those running Laravel that means the deprecation warnings will be completely masked. Even if you have Laravel's deprecation channel configured, the Laravel `HandleExceptions::shouldIgnoreDeprecationErrors` method disables deprecation warning logging when unit tests are running - I have no clue why.

Hope this additional data is helpful.

**Comment by Slamdunk** [comment] 2023-06-13 13:16
Thank you for all the precious feedbacks, this should have been fixed in https://github.com/paratestphp/paratest/pull/769 now.

**Closed as completed** 2023-06-13 13:15 UTC
Labels: bug

**Comment by lphilps** [comment] 2023-06-13 18:23
I just tried it out, and your fix works perfectly.  Many thanks!
