### ISSUE TITLE
Hard to diagnose failures with simply 'Exception'

### ISSUE THREAD

**Issue by lox** [paratestphp/paratest#125] opened 2014-11-12 07:03 UTC
We periodically have tests fail in our CI environment that show simply "Exception" at the end, despite `display_errors` enabled. 

![Image of test run](https://photos-5.dropbox.com/t/1/AADEeiZSximCFndqEmxwIhRYOebnANcuQRIEkxEqUFPCBQ/12/632579/png/1024x768/3/1415782800/0/2/Screenshot%202014-11-12%2018.01.44.png/7hzXrDE9RMHTbCA12KRm2CNjP7ayHgNJxzDcW_ATVzg)

Any suggestions?

**Comment by chbiel** [comment] 2015-01-21 12:43
I experience the same problem:

![image](https://cloud.githubusercontent.com/assets/1297702/5836262/713602e2-a173-11e4-916f-e6942595180f.png)

**Comment by julianseeger** [comment] 2015-01-31 23:29
If you have this issue on some open source projects, it would be nice if you could share a link to maybe reproduce the issue. I don't see any Exceptions paratest throws without a message (except for a NoClassInFileException, that makes no sense to happen periodically).

**Comment by sormy** [comment] 2015-06-29 19:54
I think this problem fixed in the master

**Comment by andreasschroth** [comment] 2018-05-12 06:42
As it seems to be fixed, I'm closing this issue now. Please feel free to reopen.

**Closed by andreasschroth** 2018-05-12 06:42 UTC
Labels: bug
