### ISSUE TITLE
--teamcity option

### ISSUE THREAD

**Issue by neochief** [paratestphp/paratest#595] opened 2021-02-18 14:19 UTC
There's --teamcity option in PHPUnit that changes the default output of PHPUnit from dot format (./F/E/S) to teamcity format. This may seem not that important, but this option is actually used by PHPStorm in its integration with PHPUnit.

I'm 99% sure that having this option working the same way as in PHPUnit would pave the way for PHPStorm integration with paratest (https://youtrack.jetbrains.com/issue/WI-58745).

**Comment by Slamdunk** [comment] 2021-02-18 14:23
A PR would be very welcome :+1:

**Comment by neochief** [comment] 2021-02-18 14:26
> A PR would be very welcome 👍

Okay, I'll see what I can do.

**Comment by MaXal** [comment] 2021-02-24 13:19
@neochief is right! We need this format to integrate ParaTest into PhpStorm. The dot format is not verbose enough to provide us the required information.

See https://github.com/sebastianbergmann/phpunit/blob/master/src/Util/Log/TeamCity.php for the reference.

**Comment by neochief** [comment] 2021-02-24 16:57
All right, I implemented the basic solution. @Slamdunk , can you please check it out and let me know if it is okay (https://github.com/paratestphp/paratest/pull/597)? I never contributed to Paratest or PHPUnit, so I might be missing something important. I guess I'll need to write some tests as well if the code is okayish.

During manual testing, I tricked PHPStorm by substituting phpunit binary with updated paratest and the IDE actually did it thing with running all tests, so it's a big win.

There are two caveats though:

1. To allow re-executing failed tests from within the IDE, the "filter" option needs to be compatible with PHPUnit. Currently paratest displays the "Option --filter is not implemented for non functional mode" when launching the test the way PHPStorm does this. 

2. To allow running a particular test among the test results, the "--test-suffix" should present and be compatible with PHPUnit. Currently it's not implemented.

I'm guessing these caveats are non-trivial, so I'd like Paratest maintainer's opinion on how to approach the implementation.

**Comment by arashdalir** [comment] 2021-03-15 13:06
@neochief @Slamdunk 
a question for both of you: wouldn't it be easier to use the `--log-teamcity` feature instead of reimplementing this feature? 

the `--log-teamcity` already creates the "expected result" but it needs a file to store the output (please refer to the screenshot for an example). I believe this was actually discussed while `--log-teamcity`  was being implemented [here](https://github.com/paratestphp/paratest/pull/533#issuecomment-700656480) - second screenshot - and the suggestion back then was to avoid this (with which I honestly and respectfully disagree). I realize that the caveats will probably not be resolved by using that flag, just wanted to mention this feature so in case @neochief 's implementation defers (i.e. if the feature is practically implemented twice), duplicate implementations of the same feature could be avoided. 

about the 2 caveats: would it be possible to pass them through to phpunit using `--pass-thru`?

![image](https://user-images.githubusercontent.com/2896170/111156558-2b1f6b00-8596-11eb-846b-ed5e424bd48a.png)

![image](https://user-images.githubusercontent.com/2896170/111156888-881b2100-8596-11eb-8411-3e348b02b6b8.png)

**Comment by neochief** [comment] 2021-03-15 14:00
IMHO, the closer it works to PHPUnit's implementation, the better. PHPUnit's --teamcity flag outputs directly to STDOUT, so I don't see a reason why it shouldn't behave the same way in Paratest.

As for the implementation and duplication, my code simply reuses the existing log-teamcity code, so nothing is reimplemented really.

**Comment by arashdalir** [comment] 2021-03-15 14:14
> IMHO, the closer it works to PHPUnit's implementation, the better. PHPUnit's --teamcity flag outputs directly to STDOUT, so I don't see a reason why it shouldn't behave the same way in Paratest.
> 
> As for the implementation and duplication, my code simply reuses the existing log-teamcity code, so nothing is reimplemented really.

sorry, didn't mean to say that your solution is "wrong" or "bad"; just wanted to mention that it would be great if it would reuse the same code as in `--log-teamcity` to avoid different/ contradicting behavior when one or another is used, and I agree; the closer it gets to `PHPUnit` the better because then it would be possible to reuse any existing testing procedure with `paratest` without the need to change anything else. I'd even say the "optimal" tool would provide the exact same parameters as `PHPUnit`, so that it would be simply possible to replace `php phpunit [command parameters]` with `paratest -pX [-f] [...] [command parameters]` and have everything run as before.

**Comment by Slamdunk** [comment] 2021-03-15 15:20
> I'd even say the "optimal" tool would provide the exact same parameters as `PHPUnit`

Me too, but easier to say than done: many options are incompatible with the asynchronous nature of parallel executions, and many others change so frequently that would only be a burden to provide support for, hence `--passthru` ease a lot Paratest maintainers job.

My experience as a maintainer here is that it's far better to provide a reliable API and predictable upgrades than `1:1` match with Phpunit.

Back to the `--teamcity` option: I have some issues on what problem this flag should solve.

1. https://github.com/paratestphp/paratest/pull/597 can also be achieved by `vendor/bin/paratest --log-teamcity php://stdout`
2. We need Paratest to be fast, as fast as possible: `--filter` doesn't work on single tests on purpose because it would get the overall run slower
3. As you wrote, you don't want `--teamcity`, you want PHPStorm integration, that, for now, can only be achieved by disguising Paratest as Phpunit

Sorry for the late reply, I needed that to think about this.

To have PHPStorm integration maybe it's better to dismiss https://github.com/paratestphp/paratest/pull/597 and try another path:

1. Create a separate `paratest_for_phpstorm` binary
2. Run Paratest in it with custom `@internal` flags to print teamcity output
3. When `--filter` and `--test-suffix` options are given, bypass Paratest entirely and proxy the call to bare PHPUnit

WDYT?
2. You need `--teamcity` to run it

**Comment by arashdalir** [comment] 2021-03-15 16:09
> 3. As you wrote, you don't want `--teamcity`, you want PHPStorm integration, that, for now, can only be achieved by disguising Paratest as Phpunit

I believe the [TC team has also got involved](https://youtrack.jetbrains.com/issue/WI-58745) and this feature would rather be for teamcity than for phpstorm. the bonus point is that as PS and TC are both products of the same company (jetbrains) and communicate wonderfully with each other, PS can be used to investigate test results and if needed, rerun specific tests (by providing --filter and --test-suffix and so on (@MaXal please feel free to correct me if I'm wrong).

**Comment by MaXal** [comment] 2021-03-16 08:44
There are two options for PhpStorm to implement support for paratest:
1. Pretend, this is a PHPUnit and get a lot of features out of the box but for this to be possible many command-line arguments should be the same as in PHPUnit. 
2. Implement support from scratch. That is quite a lot of work and I'm not sure whether we have enough resources at the moment to do that. 

In any case, we need the following: the support of teamcity format output to STDOUT (this allows us to parse execution on the fly and provide detailed failure messages as well as test names).

All other features are optional but without them, the support will be very limited and we will get a lot of complaint from customers since they are accustomed to them in PHPUnit:
Tier 1 support:
1. Run all tests in a single class
2. Run test method (that will enable rerun of failed tests)
3. Run all tests from the folder
4. Run `phpunit.xml` configuration
Tier 2 support:
1. Run the specific test using set `N` in the data provider.

Please note that it will be hard for us to distinguish whether paratest or PHPUnit is used in the project since our customers may have a ton of test framework configurations inside the project so we will show execution icons on the same elements as for PHPUnit and there will be complaints when, for example, running a single method doesn't work since this will force customers to go and change Test Configuration back to PHPUnit.

**Comment by arashdalir** [comment] 2021-03-16 09:08
> In any case, we need the following: the support of teamcity format output to STDOUT (this allows us to parse execution on the fly and provide detailed failure messages as well as test names).

I can confirm that @Slamdunk s idea of passing php://stdout to --log-teamcity would resolve this issue.

my XML configuration files work too; though I have simple configurations compared to those usually used. I am using XML to define a bootstrap file and my test cases. unfortunately, for some it might be necessary to define `@preserveGlobalState disabled` for the classes or functions which need to be tested in parallel in order to, well, not preserve the global state and allow parallel testing...

**Comment by Slamdunk** [comment] 2021-03-25 07:18
> 1. Pretend, this is a PHPUnit and get a lot of features out of the box but for this to be possible many command-line arguments should be the same as in PHPUnit.
> 1. Implement support from scratch. That is quite a lot of work and I'm not sure whether we have enough resources at the moment to do that.

Thank you @MaXal for the feedback.

As briefly anticipated earlier, I think the best result to effort ratio can be achieved with the first solution: a PHPUnit-like binary with the basic functionalities for Tier 1 & Tier 2 support.

I hope to be able to work on it soon

**Comment by oprypkhantc** [comment] 2022-02-01 11:20
@Slamdunk 

> When --filter and --test-suffix options are given, bypass Paratest entirely and proxy the call to bare PHPUnit

And this whole idea become obsolete then. I don't think many projects that use paratest have so few test cases they can afford to just run them locally. I believe the first thing to do is to implement above-mentioned options into paratest.

**Comment by LastDragon-ru** [comment] 2022-04-20 17:40
After an hour I have the following test tests setup for PHPStorm + Laravel (https://github.com/nunomaduro/collision) that seems works 😀 (tests can be re-run/debug because in this case the phpunit will be used). Command for paratest should be similar. The script just check args and runs tests parallel if we want to run all tests (= Run phpunit.xml in PHPStorm)

![image](https://user-images.githubusercontent.com/1329824/164287928-50fd36c3-58cb-4a3d-8af5-710faa18b85f.png)

```php
<?php declare(strict_types = 1);

use Symfony\Component\Process\Process;

// Autoload
require PHPUNIT_COMPOSER_INSTALL;

// Run
$command = implode(' ', array_slice($_SERVER['argv'], 1));

if (preg_match('/^--prepend=[^\s]+? --configuration [^\s]+? --teamcity$/ui', $command) === 1) {
    $stdout  = fopen('php://stdout', 'w');
    $stderr  = fopen('php://stderr', 'w');
    $process = new Process(['php', 'artisan', 'test', '--without-tty', '--parallel', '--log-teamcity=php://stdout']);

    $process->setTimeout(null);

    if ($stdout && $stderr) {
        $process->run(static function ($type, $buffer) use ($stdout, $stderr): void {
            if (Process::ERR === $type) {
                fwrite($stderr, $buffer);
            } else {
                fwrite($stdout, $buffer);
            }
        });
    }

    exit($process->getExitCode());
}
```

But....  These are few issues with `--log-teamcity=php://stdout` 😥

1) Count of the tests in totally wrong, I guess it is because `flowId` changes

```
Warming cache for static analysis ... done [00:00.818]

##teamcity[testCount count='3' flowId='180357']

##teamcity[testSuiteStarted ... flowId='180357']

##teamcity[testStarted name='testGetRelease' ... flowId='180357']

##teamcity[testFinished name='testGetRelease' duration='720' flowId='180357']

##teamcity[testStarted name='testGetContextBreadcrumbs' ... flowId='180357']

##teamcity[testFinished name='testGetContextBreadcrumbs' duration='65' flowId='180357']
...
##teamcity[testCount count='7' flowId='180356']

##teamcity[testSuiteStarted  flowId='180356']
```

2) Dots in Run window

![image](https://user-images.githubusercontent.com/1329824/164290162-bdc42bfc-a584-401d-81c5-c8a128441ad4.png)

3) Progress indicator run forever in some cases (eg if error)

4) Tests count is strange

![image](https://user-images.githubusercontent.com/1329824/164382265-896c64e3-b7ba-40c2-9140-1f6b5d3c9cf4.png)

5) Additional handling for `........##teamcity[testStarted` needed

![image](https://user-images.githubusercontent.com/1329824/164381818-ccb4754c-a2cb-42fa-96bc-66192da44105.png)

6) Time

![image](https://user-images.githubusercontent.com/1329824/164382075-2275a30e-c31a-4bfc-972a-db0984b4f3ba.png)


### TODOs:

1) Debug support
2) Try #597 
3) Filter out dots

**Comment by sWalbrun** [comment] 2022-06-07 09:56
Thanks @LastDragon-ru,

I am currently using your approach and added one further script to create the Test Runner Option automatically.

This script is also in `.phpunit` directory located as `testRunnerOptions.sh`.

```
# This litte script works out as long there is a .phpunit directory within the root directory having a paratest.php file

currentDirectory="$(pwd)"
# Make sure running the command also in this directory is creating a valid output
paratestAsFile="${currentDirectory%/.phpunit}/.phpunit/paratest.php"

if test ! -f "$paratestAsFile"; then
    echo "File ($paratestAsFile) is not existing!"
    exit 1
fi

echo --prepend="${paratestAsFile}"

```

**Closed** 2022-06-21 06:07 UTC
Labels: enhancement
