### ISSUE TITLE
Support testdox to stdout

### ISSUE THREAD

**Issue by greggilbert** [paratestphp/paratest#392] opened 2019-06-11 17:45 UTC
PHPUnit 7.1+ supports `--testdox`, but it's not possible to get the output to show through Paratest. `--passthru="'--testdox'"` does correctly pass it through to PHPUnit, but it doesn't print out. 

I was able to temporarily fix this by forcing the process to give incremental output (e.g. [here](https://github.com/SplashThat/paratest/commit/c5e134f2a2f4745cc61bec6b746824de2587893a)), but it'd be nice if this could be supported with Paratest. 

Just to clarify, this is most useful in places where you can't just get the testdox output, such as in CI.

**Comment by andreasschroth** [comment] 2020-02-07 22:44
Duplicate of #396 (I know this issue was created before, but the other one has more feedback now)

Thus, I close this issue.

**Closed by andreasschroth** 2020-02-07 22:44 UTC
