### ISSUE TITLE
Paratest proccess hangs and does not respond

### ISSUE THREAD

**Issue by salexfo** [paratestphp/paratest#206] opened 2016-05-24 13:00 UTC
Hi, I'm trying to utilize paratest to accelerate moodle unit testing. I've installed paratest via composer and when I try to run it via sudo vendor/bin/paratest -p 4 -c phpunit.xml
it just gets stuck and doesn't react. When using ps auxf I can see that the processes have the status: S+. 

Can anyone assist?

Thanks,
Alexander

**Comment by julianseeger** [comment] 2016-05-24 13:21
Are you testing the https://github.com/moodle/moodle master ?
Btw.: you shouldn't need a `sudo` on your tests. more generally you shouldn't need a sudo at all when using composer and if you need it, you should change what makes you need it

**Comment by salexfo** [comment] 2016-05-24 13:26
@julianseeger yes, we are.

**Comment by salexfo** [comment] 2016-05-26 11:21
can someone assist?

**Comment by donkeyx** [comment] 2016-07-27 22:35
--bump-- 
I am having the same problem, would be good to see some movement? I have tried using WrapperRunner but same problem in getting stuck after "configuration read from". The text below is where it gets too but no further. 

[root@d2a816dda349 html]# vendor/bin/paratest -p 10 --runner WrapperRunner
Moodle 2.7.13 (Build: 20160314), pgsql, c55b93c6d6656b896b1f2da1c3ac7760fbc86fab

Running phpunit in 10 processes with /var/www/html/vendor/bin/phpunit

Configuration read from /var/www/html/phpunit.xml

**Comment by doratias** [comment] 2016-09-30 12:25
does anyone already solved this issue?

**Comment by asuth** [comment] 2017-02-19 18:16
We experienced this issue and tracked it down to the following code that was part of a `set_error_handler` callback. Paratest would not report the error, and hang, if we had a php error somewhere in our code, e.g. (division by zero `1/0` somewhere in our code).

```php
$stdErr = fopen('php://stderr', 'w');
fwrite($stdErr, $errorMessage);
fclose($stdErr);
```

I assume because paratest parses stderr, it doesn't expect arbitrary stuff. Would be nice if paratest had more guards against this.

**Comment by michaelbutler** [comment] 2017-02-23 02:55
Agreed, I believe I have experienced the same or very similar bug.  It would be helpful to have a simple reproduce script to test against so we could fix it.  One thing I noticed is that when using a custom test wrapper (or listener) along with wrapperrunner causes the hang..  But regular runner shouldn't.

**Comment by michaelbutler** [comment] 2017-02-23 02:55
Also,  what version of php are you using?

**Comment by asuth** [comment] 2017-02-23 02:57
We use HHVM 3.14.5

**Comment by andreasschroth** [comment] 2018-05-12 06:39
I'm closing this now. Without a concrete script to reproduce the problem, I doubt it can be fixed. Please everyone feel free to reopen if you have further information about this, thank you.

**Closed by andreasschroth** 2018-05-12 06:39 UTC
Labels: bug
