### ISSUE TITLE
Incorrect Coverage report with PHPunit 6.3 and PHP 7.1

### ISSUE THREAD

**Issue by celowsky** [paratestphp/paratest#278] opened 2017-09-21 17:20 UTC
With the latest stable/supported releases of PHPunit, PHP, and Paratest, it appears that the coverage report generated by Paratest is incorrectly reporting lines as not covered. These include opening and closing braces and brackets for functions and arrays, as well as closing parenthesis for function calls. 
![incorrectcodecoverage](https://user-images.githubusercontent.com/5439675/30709223-26583854-9ec7-11e7-9ff2-e55b886e5cb2.png)

**Comment by celowsky** [comment] 2017-10-04 01:59
The test suite is currently being run on a Symfony 3.3 project.

**Comment by willemstuursma** [comment] 2017-10-04 14:01
In xdebug there are covered lines, uncovered lines and dead code. Probably that last one is not passed through correctly.

**Comment by michaelbutler** [comment] 2018-04-12 14:24
@celowsky there was a bug in Xdebug that was fixed (I experienced it myself)... could you double check your Xdebug version (`php -v`) and report back? Upgrade to Xdebug 2.6.0 and see if the issue is fixed.

**Comment by andreasschroth** [comment] 2018-05-12 10:11
I'll close this issue now. @celowsky Please feel free to reopen the issue in case the problem still occurs.

**Closed by andreasschroth** 2018-05-12 10:11 UTC
